---
name: Pull Request
on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: pull_request-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr:
    uses: JamesWoolfenden/.github/.github/workflows/terraform-pr.yml@7e6376f276d0f76e4565243d9c443330804b960e # main
